version: '3.8'

services:
  feb2024-postgres:
    image: postgres:16-alpine
    ports:
      - '${POSTGRES_PORT:-5432}:5432'
    environment:
      POSTGRES_USER: '${POSTGRES_USER:-pguser}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD:-pgpassword}'
      POSTGRES_DB: '${POSTGRES_DB:-feb2024}'
    volumes:
      - ./feb2024-api-db:/var/lib/postgresql/data

  feb2024-redis:
    image: redis:alpine
    ports:
      - '${REDIS_PORT:-6379}:6379'
    command: >
      --requirepass '${REDIS_PASSWORD:-redispassword}'
    restart: on-failure

  feb2024-s3:
    image: quay.io/minio/minio:latest
    command: server /data --console-address ":9001"
    restart: on-failure
    ports:
      - "7002:9000"
      - "7001:9001"
    volumes:
      - ./feb2024-api-s3:/usr/src/app/s3
    environment:
      - MINIO_ROOT_USER=s3user
      - MINIO_ROOT_PASSWORD=s3password

volumes:
  feb2024-api-db:
  feb2024-api-s3:
